### PR TITLE
nodejs: validate body string type

### LINKED ISSUE #84: nodejs: object body can be wrongly used without error
## Bug description

Javascript lib allow signing a object body `{foo:123}` instead of the correct string serialization `"{\"foo\":123}"` without error. However, it won't generate a usable signature so will always fail.

## Expected behavior

We should error when the incorrect type is used here.

### PR DESCRIPTION
**Pull request by alexheretic**
Add validation that `body` is a string. This can otherwise silently produce a useless signature.

Resolves #84

### CODE REVIEW

File: nodejs/src/lib.ts [hunk 1]
```diff
@@ -37,6 +37,9 @@ const buildV2SigningPayload = ({
   if (!path.startsWith('/')) {
     throw new Error(`Invalid path \"${path}\" must start with '/'`);
   }
+  if (!(typeof body === 'string' || (body as any) instanceof String)) {
+    throw new Error(`Invalid body '${typeof body}' type must be a string`);
+  }
```
Comment (tl-sebastien-kovacs) [inline nodejs/src/lib.ts:42]: ❤️

**Review by tl-sebastien-kovacs — APPROVED** [review]
Thanks !
